### ISSUE TITLE
Traceback when marker is called with no arguments

### ISSUE THREAD

**Issue by siddharthist** [pindexis/marker#24]
Maybe the help text should be shown instead? 
```
dotfiles ➤ marker
Traceback (most recent call last):
  File "/home/siddharthist/.local/share/marker-git/bin/marker", line 65, in <module>
    parse_arguments()
  File "/home/siddharthist/.local/share/marker-git/bin/marker", line 31, in parse_arguments
    return args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by adiba** [comment]
Hey @langston-barrett , were you able to resolve this issue?
