### ISSUE TITLE
Python 3.7.3 - TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by jorgevleberton** [pindexis/marker#66]
Traceback (most recent call last):
  File "C:\Users\jorge\Documents\MESTRADO - ENGENHARIA DE ENERGIAS - UNIFEI\DISSERTAÇÃO\Dissertação - Tiago\REFERÊNCIAS\SIMULAÇÃO\BASE TEÓRICA\Utilities-of-the-Future-master\2-Utility_Death_Spiral\Main_Static.py", line 115, in <module>
    wb.close()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\workbook.py", line 304, in close
    self._store_workbook()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\workbook.py", line 646, in _store_workbook
    xml_files = packager._create_package()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\packager.py", line 143, in _create_package
    self._write_shared_strings_file()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\packager.py", line 287, in _write_shared_strings_file
    sst._assemble_xml_file()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\sharedstrings.py", line 54, in _assemble_xml_file
    self._write_sst_strings()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\sharedstrings.py", line 84, in _write_sst_strings
    self._write_si(string)
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xlsxwriter\sharedstrings.py", line 96, in _write_si
    string = re.sub('(_x[0-9a-fA-F]{4}_)', r'_x005F\1', string)
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python37-32\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by CounterPly** [comment]
Change line 61 of install.py from

```python
m = re.search('(\d).(\d)', version_text)
```
to...

```python
m = re.search('(\d).(\d)', version_text.decode('utf-8'))
```

**Comment by negora** [comment]
I had the same problem with the latest version of `marker` in Debian 11. The fix proposed by @CounterPly has resolved the problem.
