### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by PrzemekSkw** [pindexis/marker#76]
Hello, I try to install on Archlinux (EndevourOS):
```
➜ sudo git clone --depth=1 https://github.com/pindexis/marker ~/.marker && ~/.marker/install.py
Klonowanie do „/home/mariank/.marker”...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 25 (delta 0), reused 9 (delta 0), pack-reused 0
Pobieranie obiektów: 100% (25/25), 54.78 KiB | 849.00 KiB/s, gotowe.
Traceback (most recent call last):
  File "/home/mariank/.marker/install.py", line 97, in <module>
    main()
  File "/home/mariank/.marker/install.py", line 81, in main
    verify_requirements()
  File "/home/mariank/.marker/install.py", line 61, in verify_requirements
    m = re.search('(\d).(\d)', version_text)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```
Regards.

**Comment by binarymelon** [comment]
@PrzemekSkw Did you find a workaround?

**Comment by PrzemekSkw** [comment]
@binarymelon no I did not.
Regards

**Comment by binarymelon** [comment]
@PrzemekSkw Adding `.decode('UTF-8')` to the following line should do it.

https://github.com/pindexis/marker/blob/ef68f2a26fe479f75bbaf5c30d3cd0fd7fd45a45/install.py#L60

**Comment by PrzemekSkw** [comment]
Thanks, that works.
Regards.
